### ISSUE TITLE
License and forking

### ISSUE THREAD

**Issue by JoelESvensson** [alxy/oc-facebook-plugin#2]
Hi! I read somewhere that you are not supporting this anymore. Is it okay if I continue development of the plugin as a fork? If agreed on it I'll license the plugin as MIT

**Comment by alxy** [comment]
Is ok... I can even merge merge PRs and update the plugin :)

**Comment by vojtasvoboda** [comment]
How about transfer plugin and repository ownership?

**Comment by alxy** [comment]
@vojtasvoboda I added you as collaborator, so you can add patches whenever you want :)

**Comment by vojtasvoboda** [comment]
Great :-) Thanks!
